/**
 * Cashing out: the merchant's USDC to a payout partner's deposit address.
 *
 * The partner (paj.cash) takes crypto at an address and pays naira to a bank.
 * So a cash-out is an ordinary token transfer, signed by the merchant, with
 * Nelo's relayer as fee payer so the merchant still needs no SOL.
 *
 * The relayer builds the transaction and signs only a message it built, so
 * it never has to parse a transaction someone else wrote to decide whether
 * paying for it is safe. The merchant's wallet signs second; `checkOwnerSigned`
 * refuses anything but the exact message, carrying a valid owner signature.
 *
 * Both instructions are pinned to `vectors/redeem-v1.json`, generated by the
 * SPL crates themselves in `programs/nelo_vault/tests/tx_vectors.rs`.
 */
import { getTransactionDecoder, getTransactionEncoder } from "@solana/kit";
import { ed25519 } from "@noble/curves/ed25519";
import { decodeBase58, encodeBase58 } from "@nelo/voucher";
import { addressBytes, associatedTokenAddress, ASSOCIATED_TOKEN_PROGRAM_ID, TOKEN_PROGRAM_ID } from "./address.ts";
import { AccountRole, SYSTEM_PROGRAM_ID, type Instruction } from "./index.ts";
import { buildTransaction, type Lifetime, type Unsigned } from "./transaction.ts";

/** The token program's `TransferChecked`. */
const TRANSFER_CHECKED = 12;
/** The ATA program's `CreateIdempotent`: succeeds, and does nothing, if the account exists. */
const CREATE_IDEMPOTENT = 1;

export function transferCheckedInstruction(input: {
  owner: string;
  destinationOwner: string;
  mint: string;
  amount: bigint;
  decimals: number;
  tokenProgram?: string;
}): Instruction {
  const tokenProgram = input.tokenProgram ?? TOKEN_PROGRAM_ID;
  if (input.amount <= 0n || input.amount >= 1n << 64n) throw new RangeError("amount must be a positive u64");
  if (!Number.isInteger(input.decimals) || input.decimals < 0 || input.decimals > 255) {
    throw new RangeError("decimals must be a u8");
  }
  const data = new Uint8Array(10);
  data[0] = TRANSFER_CHECKED;
  new DataView(data.buffer).setBigUint64(1, input.amount, true);
  data[9] = input.decimals;
  return {
    programAddress: tokenProgram,
    accounts: [
      { address: associatedTokenAddress(input.owner, input.mint, tokenProgram), role: AccountRole.WRITABLE },
      { address: input.mint, role: AccountRole.READONLY },
      { address: associatedTokenAddress(input.destinationOwner, input.mint, tokenProgram), role: AccountRole.WRITABLE },
      { address: input.owner, role: AccountRole.READONLY_SIGNER },
    ],
    data,
  };
}

/** Open the deposit address's token account if it has none, paid by `payer`. */
export function createDepositAccountInstruction(input: {
  payer: string;
  owner: string;
  mint: string;
  tokenProgram?: string;
}): Instruction {
  const tokenProgram = input.tokenProgram ?? TOKEN_PROGRAM_ID;
  return {
    programAddress: ASSOCIATED_TOKEN_PROGRAM_ID,
    accounts: [
      { address: input.payer, role: AccountRole.WRITABLE_SIGNER },
      { address: associatedTokenAddress(input.owner, input.mint, tokenProgram), role: AccountRole.WRITABLE },
      { address: input.owner, role: AccountRole.READONLY },
      { address: input.mint, role: AccountRole.READONLY },
      { address: SYSTEM_PROGRAM_ID, role: AccountRole.READONLY },
      { address: tokenProgram, role: AccountRole.READONLY },
    ],
    data: Uint8Array.of(CREATE_IDEMPOTENT),
  };
}

export interface CashoutInput {
  /** The merchant: signs, and the tokens are theirs. */
  owner: string;
  /** The partner's deposit address for this order. */
  deposit: string;
  mint: string;
  amount: bigint;
  decimals: number;
  /** The relayer: pays the fee. */
  feePayer: string;
  /** Also open the deposit address's token account, paid by the fee payer. */
  createDepositAccount: boolean;
  tokenProgram?: string;
}

/** The transfer, fee paid by the relayer, signed by the merchant. */
export function buildCashout(input: CashoutInput, lifetime: Lifetime): Unsigned {
  addressBytes(input.owner);
  addressBytes(input.deposit);
  if (input.owner === input.feePayer) throw new Error("the merchant cannot be the fee payer here");
  const instructions: Instruction[] = [];
  if (input.createDepositAccount) {
    instructions.push(createDepositAccountInstruction({ payer: input.feePayer, owner: input.deposit, mint: input.mint, ...(input.tokenProgram ? { tokenProgram: input.tokenProgram } : {}) }));
  }
  instructions.push(
    transferCheckedInstruction({
      owner: input.owner,
      destinationOwner: input.deposit,
      mint: input.mint,
      amount: input.amount,
      decimals: input.decimals,
      ...(input.tokenProgram ? { tokenProgram: input.tokenProgram } : {}),
    }),
  );
  return buildTransaction(instructions, input.feePayer, lifetime);
}

export type OwnerSigned = { ok: true; wire: Uint8Array } | { ok: false; reason: string };

/**
 * Accept the merchant's signed bytes only if they are the message that was
 * built, carrying a valid signature from `owner`. The fee payer's slot is the
 * relayer's to fill; anything the wallet put there is ignored.
 */
export function checkOwnerSigned(unsigned: Unsigned, signedWire: Uint8Array, owner: string): OwnerSigned {
  let decoded: ReturnType<ReturnType<typeof getTransactionDecoder>["decode"]>;
  try {
    decoded = getTransactionDecoder().decode(signedWire);
  } catch {
    return { ok: false, reason: "not a transaction" };
  }
  const message = new Uint8Array(decoded.messageBytes);
  if (message.length !== unsigned.message.length || !message.every((b, i) => b === unsigned.message[i])) {
    return { ok: false, reason: "the wallet changed the transaction before signing it" };
  }
  const signature = (decoded.signatures as Record<string, Uint8Array | null>)[owner];
  if (!signature || signature.every((b) => b === 0)) return { ok: false, reason: "the merchant did not sign" };
  if (!ed25519.verify(signature, message, decodeBase58(owner))) {
    return { ok: false, reason: "the merchant's signature does not verify" };
  }
  return { ok: true, wire: new Uint8Array(signedWire) };
}

/** Put `signer`'s signature into its slot. Returns the new wire and the transaction id if `signer` pays. */
export function withSignature(wire: Uint8Array, signer: string, signature: Uint8Array): Uint8Array {
  const decoded = getTransactionDecoder().decode(wire);
  const signatures = decoded.signatures as Record<string, Uint8Array | null>;
  if (!(signer in signatures)) throw new Error(`${signer} is not a signer of this transaction`);
  const updated = { ...decoded, signatures: { ...signatures, [signer]: signature } };
  return new Uint8Array(getTransactionEncoder().encode(updated as never));
}

/** A transaction's id is its fee payer's signature. */
export function transactionId(signature: Uint8Array): string {
  return encodeBase58(signature);
}
