/**
 * The TypeScript half of the wire-format contract.
 *
 * `vectors/voucher-v1.json` is generated by the Rust side, which is what the
 * chain actually verifies against. If these tests fail, the phone and the chain
 * disagree about the bytes — which on chain surfaces as a signature that will
 * not verify, for reasons that look nothing like a layout bug.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { p256 } from "@noble/curves/p256";
import {
  decode,
  derToRawSignature,
  encode,
  isLowS,
  compressPublicKey,
  signedMessage,
  verify,
  SIGNED_LEN,
  VOUCHER_LEN,
  type Voucher,
} from "../src/index.ts";

const vectorsPath = fileURLToPath(new URL("../vectors/voucher-v1.json", import.meta.url));
const vectors = JSON.parse(readFileSync(vectorsPath, "utf8")) as VectorCase[];

interface VectorCase {
  name: string;
  fields: {
    version: number;
    vault: string;
    seq: string;
    amount: string;
    remainingAfter: string;
    merchant: string;
    expiresAt: string;
    salt: string;
  };
  signature: string;
  devicePubkey: string;
  signedHex: string;
  packetHex: string;
}

const unhex = (s: string): Uint8Array =>
  Uint8Array.from(s.match(/../g)!.map((b) => parseInt(b, 16)));
const hex = (b: Uint8Array): string =>
  [...b].map((x) => x.toString(16).padStart(2, "0")).join("");

const toVoucher = (c: VectorCase): Voucher => ({
  version: c.fields.version,
  vault: unhex(c.fields.vault),
  seq: BigInt(c.fields.seq),
  amount: BigInt(c.fields.amount),
  remainingAfter: BigInt(c.fields.remainingAfter),
  merchant: unhex(c.fields.merchant),
  expiresAt: BigInt(c.fields.expiresAt),
  salt: unhex(c.fields.salt),
  signature: unhex(c.signature),
  devicePubkey: unhex(c.devicePubkey),
});

test("vectors file is present and non-empty", () => {
  assert.ok(vectors.length > 0, "no golden vectors — regenerate from the Rust side");
});

for (const c of vectors) {
  test(`[${c.name}] signed message matches the chain byte for byte`, () => {
    const mine = signedMessage(toVoucher(c));
    assert.equal(mine.length, SIGNED_LEN);
    assert.equal(hex(mine), c.signedHex);
  });

  test(`[${c.name}] full 202-byte packet matches`, () => {
    const packet = encode(toVoucher(c));
    assert.equal(packet.length, VOUCHER_LEN);
    assert.equal(hex(packet), c.packetHex);
  });

  test(`[${c.name}] decode round-trips`, () => {
    const original = toVoucher(c);
    const back = decode(unhex(c.packetHex));
    assert.equal(back.version, original.version);
    assert.equal(back.seq, original.seq);
    assert.equal(back.amount, original.amount);
    assert.equal(back.remainingAfter, original.remainingAfter);
    assert.equal(back.expiresAt, original.expiresAt, "i64 must survive, including negatives");
    assert.equal(hex(back.vault), hex(original.vault));
    assert.equal(hex(back.merchant), hex(original.merchant));
    assert.equal(hex(back.salt), hex(original.salt));
    assert.equal(hex(encode(back)), c.packetHex);
  });

  test(`[${c.name}] verifies a signature the Rust side produced`, () => {
    // The strong form of the cross-language check: these signatures were made
    // by the Rust test key over Rust-built bytes.
    assert.equal(verify(toVoucher(c)), true);
  });

  test(`[${c.name}] rejects a tampered amount`, () => {
    const tampered = toVoucher(c);
    tampered.amount = tampered.amount + 1n;
    assert.equal(verify(tampered), false);
  });
}

// ---------------------------------------------------------- length guards ---

test("decode refuses anything that is not 202 bytes", () => {
  assert.throws(() => decode(new Uint8Array(201)), /202 bytes/);
  assert.throws(() => decode(new Uint8Array(203)), /202 bytes/);
});

test("decode refuses an unknown version", () => {
  const bytes = unhex(vectors[0]!.packetHex);
  bytes[0] = 2;
  assert.throws(() => decode(bytes), /version/);
});

// -------------------------------------------------- DER -> raw conversion ---

test("noble's p256 does NOT default to low-S", () => {
  // Load-bearing: any signature this library produces without `lowS: true` has
  // roughly a 50% chance of being rejected by the on-chain precompile. Every
  // TypeScript signing path must normalise, and this test is here so that fact
  // is discovered by a red test rather than by a failing redemption.
  const key = fixedKey();
  const half = p256.CURVE.n / 2n;
  let high = 0;
  for (let i = 0; i < 64; i++) {
    const msg = new Uint8Array(32);
    msg[0] = i;
    if (p256.sign(msg, key, { prehash: true }).s > half) high++;
  }
  assert.ok(high > 0, "expected some high-S signatures from the default path");
  for (let i = 0; i < 64; i++) {
    const msg = new Uint8Array(32);
    msg[0] = i;
    assert.ok(
      p256.sign(msg, key, { prehash: true, lowS: true }).s <= half,
      "lowS:true must always produce low-S",
    );
  }
});

test("DER converts to 64 raw bytes, r||s", () => {
  const key = fixedKey();
  const msg = new Uint8Array(105).fill(7);
  const sig = p256.sign(msg, key, { prehash: true, lowS: true });
  const raw = derToRawSignature(sig.toDERRawBytes());

  assert.equal(raw.length, 64);
  assert.equal(hex(raw), hex(sig.toCompactRawBytes()), "low-S input passes through unchanged");
});

test("DER conversion folds a high-S signature to low-S", () => {
  // Android will hand back high-S signatures. They verify fine on the phone
  // and are refused on chain, which is the trap this function exists for.
  const key = fixedKey();
  const pub = p256.getPublicKey(key, true);
  const msg = new Uint8Array(105).fill(3);
  const low = p256.sign(msg, key, { prehash: true, lowS: true });

  const high = new p256.Signature(low.r, p256.CURVE.n - low.s);
  assert.equal(isLowS(high.toCompactRawBytes()), false, "constructed a high-S signature");

  const raw = derToRawSignature(high.toDERRawBytes());
  assert.equal(isLowS(raw), true, "must be folded to low-S");
  assert.equal(hex(raw), hex(low.toCompactRawBytes()), "folds back to the canonical form");
  assert.equal(p256.verify(raw, msg, pub, { prehash: true }), true, "still a valid signature");
});

test("DER conversion rejects malformed input", () => {
  assert.throws(() => derToRawSignature(new Uint8Array([0x31, 0x02])), /malformed DER/);
  assert.throws(() => derToRawSignature(new Uint8Array([0x30, 0x99, 0x02])), /malformed DER/);
});

/** Deterministic, so a failure reproduces instead of appearing one run in two. */
function fixedKey(): Uint8Array {
  const k = new Uint8Array(32).fill(1);
  k[31] = 7;
  return k;
}

// ------------------------------------------------- public key compression ---

test("compresses an Android uncompressed point to SEC1", () => {
  // Cross-checked against noble rather than against itself: noble computes the
  // compressed form independently from the private key.
  for (const seed of [1, 7, 42, 200]) {
    const priv = new Uint8Array(32).fill(1);
    priv[31] = seed;
    const uncompressed = p256.getPublicKey(priv, false);
    const expected = p256.getPublicKey(priv, true);
    assert.equal(uncompressed.length, 65);
    assert.equal(hex(compressPublicKey(uncompressed)), hex(expected), `seed ${seed}`);
  }
});

test("compression rejects malformed points", () => {
  assert.throws(() => compressPublicKey(new Uint8Array(64)), /65 bytes/);
  const badPrefix = new Uint8Array(65);
  badPrefix[0] = 0x02;
  assert.throws(() => compressPublicKey(badPrefix), /0x04/);
});
